### ISSUE TITLE
Cannot seem to install addon

### ISSUE THREAD

**Issue by ghost** [cnisidis/blend4vcam#1]
I can't install this addon onto any version of blender I have.  I've been trying with Blender 2.70 as that appears to be the main version this addon was made for, but I keep getting similar errors.  This image shows what happen when I try to install it:
![Desktop-1611605934569](https://user-images.githubusercontent.com/69369995/105761951-bfb80600-5f21-11eb-892c-710681134247.gif)

**Comment by cnisidis** [comment]
Hello, thanks for the remark, I ll check it asap. Unfortunately you should consider this project as obsolete and closed. Although I ll try to update it in a newer blender version (2.83+).

**Comment by ghost** [comment]
I understand.  You don't have to work on it if you don't have the time.  Thank you very much for responding!
